-- generated by scripts/gen-seed.mts
begin;
insert into public.menu_categories (id, name_hu, name_en, sort) values
('soups', 'Levesek', 'Soups', 1),
('mains', 'Főételek', 'Mains', 2),
('street', 'Bisztró klasszikusok', 'Bistro classics', 3),
('desserts', 'Desszertek', 'Desserts', 4),
('drinks', 'Italok', 'Drinks', 5)
on conflict (id) do update set name_hu = excluded.name_hu, name_en = excluded.name_en, sort = excluded.sort;
insert into public.menu_items (id, category_id, name_hu, name_en, description_hu, description_en, price, tags, image, quick, signature, sort) values
('gulyas', 'soups', 'Bográcsgulyás', 'Kettle goulash', 'Marhalábszár, sok paprika, csipetke. Reggel óta rotyog.', 'Beef shin, plenty of paprika, pinched noodles. Bubbling since morning.', 2890, array['spicy']::text[], 'https://images.unsplash.com/photo-1748309280994-bb23a2f600cc', '{"time":"5 min","side":{"hu":"Házi kenyér","en":"House bread"},"protein":"28 g","spice":2,"kcal":540}'::jsonb, true, 0),
('ujhazi', 'soups', 'Újházi tyúkhúsleves', 'Újházi chicken soup', 'Tiszta húsleves cérnametélttel, zöldséggel, főtt hússal.', 'Clear chicken broth with fine noodles, root veg and tender meat.', 2290, array[]::text[], null, '{"time":"5 min","side":{"hu":"Cérnametélt","en":"Fine noodles"},"protein":"24 g","spice":0,"kcal":380}'::jsonb, false, 1),
('paprikas', 'mains', 'Csirkepaprikás nokedlivel', 'Chicken paprikash', 'Tejfölös paprikás szósz, házi nokedli, uborkasaláta.', 'Sour-cream paprika sauce, house nokedli dumplings, cucumber salad.', 4690, array['spicy']::text[], 'https://images.unsplash.com/photo-1537516803400-bf9d09ae3d2f', '{"time":"12 min","side":{"hu":"Nokedli","en":"Nokedli"},"protein":"38 g","spice":1,"kcal":820}'::jsonb, true, 2),
('toltott', 'mains', 'Töltött káposzta', 'Stuffed cabbage', 'Savanyú káposztában főtt töltelék, füstölt oldalas, tejföl.', 'Pork-and-rice rolls slow-cooked in sauerkraut, smoked ribs, sour cream.', 4490, array['gluten-free']::text[], 'https://images.unsplash.com/photo-1622220734058-23ce1f89d84d', '{"time":"10 min","side":{"hu":"Friss kenyér","en":"Fresh bread"},"protein":"34 g","spice":1,"kcal":760}'::jsonb, true, 3),
('rantott', 'mains', 'Rántott szelet', 'Breaded pork schnitzel', 'Ropogós bundában, petrezselymes újburgonyával és áfonyával.', 'Crisp crumb, parsley new potatoes and cranberry on the side.', 4990, array[]::text[], 'https://images.unsplash.com/photo-1599921841143-819065a55cc6', '{"time":"14 min","side":{"hu":"Petrezselymes burgonya","en":"Parsley potatoes"},"protein":"42 g","spice":0,"kcal":940}'::jsonb, true, 4),
('lecso-bowl', 'mains', 'Lecsós zöldségtál', 'Lecsó veggie bowl', 'Paprikás lecsó, sült csicseriborsó, friss saláta, pirított mag.', 'Pepper-and-tomato lecsó, roast chickpeas, fresh greens, toasted seeds.', 3790, array['vegan','gluten-free']::text[], 'https://images.unsplash.com/photo-1547496502-affa22d38842', '{"time":"8 min","side":{"hu":"Saláta","en":"Greens"},"protein":"18 g","spice":1,"kcal":560}'::jsonb, true, 5),
('rotyi-burger', 'street', 'Rotyi burger', 'Rotyi burger', 'Mangalica-marha húspogácsa, füstölt sajt, paprikás majonéz.', 'Mangalica-beef patty, smoked cheese, paprika mayo, brioche bun.', 5290, array[]::text[], 'https://images.unsplash.com/photo-1534790566855-4cb788d389ec', '{"time":"12 min","side":{"hu":"Hasábburgonya","en":"Fries"},"protein":"40 g","spice":1,"kcal":980}'::jsonb, true, 6),
('csirkefalatok', 'street', 'Rántott csirkefalatok', 'Crispy chicken bites', 'Kukoricapelyhes bunda, fokhagymás-tejfölös mártogatós.', 'Cornflake crumb, garlic sour-cream dip.', 3990, array[]::text[], 'https://images.unsplash.com/photo-1562967916-eb82221dfb92', '{"time":"10 min","side":{"hu":"Mártogatós","en":"Dip"},"protein":"32 g","spice":0,"kcal":690}'::jsonb, false, 7),
('langos', 'street', 'Lángos sajttal, tejföllel', 'Lángos, cheese & sour cream', 'Frissen sütött, fokhagymás. Pont mint a Balatonon.', 'Fried to order, garlic-brushed. Just like at Lake Balaton.', 1990, array['vegetarian']::text[], null, '{"time":"6 min","side":{"hu":"Fokhagyma","en":"Garlic"},"protein":"16 g","spice":0,"kcal":720}'::jsonb, false, 8),
('gundel', 'desserts', 'Gundel-palacsinta', 'Gundel pancake', 'Diós töltelék, rumos csokoládéöntet.', 'Walnut filling, rum-chocolate sauce.', 2490, array['vegetarian']::text[], 'https://images.unsplash.com/photo-1565087170449-fa23854a6100', '{"time":"6 min","side":{"hu":"Csokiöntet","en":"Choc sauce"},"protein":"9 g","spice":0,"kcal":520}'::jsonb, false, 9),
('turos', 'desserts', 'Túrós palacsinta eperrel', 'Túró pancake with strawberries', 'Vaníliás túró, friss eper, tejszínhab.', 'Vanilla curd cheese, fresh strawberries, whipped cream.', 1990, array['vegetarian']::text[], 'https://images.unsplash.com/photo-1587314168485-3236d6710814', '{"time":"6 min","side":{"hu":"Tejszínhab","en":"Whipped cream"},"protein":"14 g","spice":0,"kcal":470}'::jsonb, false, 10),
('somloi', 'desserts', 'Somlói galuska', 'Somlói sponge trifle', 'Piskóta, vaníliakrém, dió, csoki, tejszín. Nagyi receptje.', 'Sponge, vanilla custard, walnut, chocolate, cream. Grandma''s recipe.', 2290, array['vegetarian']::text[], null, '{"time":"3 min","side":{"hu":"Csokiszósz","en":"Choc sauce"},"protein":"8 g","spice":0,"kcal":560}'::jsonb, false, 11),
('sor', 'drinks', 'Kézműves világos sör 0,5 l', 'Craft lager 0.5 l', 'Budapesti kisüzemi főzde, csapról.', 'Small-batch Budapest brewery, on tap.', 1690, array['vegan']::text[], 'https://images.unsplash.com/photo-1618183479302-1e0aa382c36b', '{"time":"1 min","side":{"hu":"Csapról","en":"On tap"},"protein":"—","spice":0,"kcal":215}'::jsonb, false, 12),
('limonade', 'drinks', 'Házi limonádé 0,5 l', 'House lemonade 0.5 l', 'Bodza, citrom vagy málna-menta.', 'Elderflower, lemon or raspberry-mint.', 1290, array['vegan','gluten-free']::text[], null, '{"time":"2 min","side":{"hu":"Jég","en":"Ice"},"protein":"—","spice":0,"kcal":140}'::jsonb, false, 13),
('froccs', 'drinks', 'Fröccs (2+1)', 'Spritzer (2+1)', 'Száraz fehérbor szódával, ahogy illik.', 'Dry Hungarian white wine with soda, the local way.', 990, array['vegan','gluten-free']::text[], null, '{"time":"1 min","side":{"hu":"Szóda","en":"Soda"},"protein":"—","spice":0,"kcal":110}'::jsonb, false, 14)
on conflict (id) do nothing;
insert into public.daily_lunch (weekday, soup_hu, soup_en, main_hu, main_en, dessert_hu, dessert_en) values
(0, 'Zöldborsóleves', 'Green pea soup', 'Paprikás krumpli virslivel', 'Paprika potatoes with sausage', 'Mákos guba', 'Poppy-seed bread pudding'),
(1, 'Gombakrémleves', 'Cream of mushroom', 'Sertéspörkölt tarhonyával', 'Pork pörkölt with tarhonya', 'Almás rétes', 'Apple strudel'),
(2, 'Jókai bableves', 'Jókai bean soup', 'Rakott krumpli', 'Layered potato bake', 'Túrógombóc', 'Túró dumplings'),
(3, 'Palócleves', 'Palóc lamb soup', 'Csirkepaprikás nokedlivel', 'Chicken paprikash with nokedli', 'Kakaós csiga', 'Cocoa swirl'),
(4, 'Halászlé (kicsi)', 'Fisherman''s soup (small)', 'Rántott sajt rizzsel, tartárral', 'Fried cheese, rice, tartar', 'Somlói galuska', 'Somlói sponge trifle')
on conflict (weekday) do nothing;
insert into public.dining_tables (label, seats, area) values
('T1', 2, 'window'),
('T2', 2, 'window'),
('T3', 4, 'inside'),
('T4', 4, 'inside'),
('T5', 4, 'inside'),
('T6', 6, 'inside'),
('T7', 6, 'inside'),
('T8', 8, 'inside'),
('B1', 2, 'bar'),
('B2', 2, 'bar'),
('K1', 4, 'terrace'),
('K2', 4, 'terrace')
on conflict (label) do nothing;
insert into public.staff_invites (email, role, name) values ('admin@example.com', 'admin', 'Owner') on conflict (email) do nothing;
update public.settings set owner_email = 'admin@example.com' where owner_email is null;
commit;
