// Generates supabase/seed.sql from the site's static content so the database
// starts identical to what the website already shows.
import { writeFileSync } from "node:fs";
import { categories, dailyLunch, menuItems } from "../src/lib/menu.ts";

const q = (v: unknown) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a: string[]) => `array[${a.map(q).join(",")}]::text[]`;

const lines: string[] = ["-- generated by scripts/gen-seed.mts", "begin;"];
lines.push(
  "insert into public.menu_categories (id, name_hu, name_en, sort) values",
  categories.map((c) => `(${q(c.id)}, ${q(c.name.hu)}, ${q(c.name.en)}, ${c.sort})`).join(",\n") +
    "\non conflict (id) do update set name_hu = excluded.name_hu, name_en = excluded.name_en, sort = excluded.sort;",
);
lines.push(
  "insert into public.menu_items (id, category_id, name_hu, name_en, description_hu, description_en, price, tags, image, quick, signature, sort) values",
  menuItems
    .map(
      (m, i) =>
        `(${q(m.id)}, ${q(m.categoryId)}, ${q(m.name.hu)}, ${q(m.name.en)}, ${q(m.description.hu)}, ${q(m.description.en)}, ${m.price}, ${arr(m.tags)}, ${q(m.image ?? null)}, ${q(JSON.stringify(m.quick))}::jsonb, ${m.signature ? "true" : "false"}, ${i})`,
    )
    .join(",\n") + "\non conflict (id) do nothing;",
);
lines.push(
  "insert into public.daily_lunch (weekday, soup_hu, soup_en, main_hu, main_en, dessert_hu, dessert_en) values",
  dailyLunch
    .map((d, i) => `(${i}, ${q(d.soup.hu)}, ${q(d.soup.en)}, ${q(d.main.hu)}, ${q(d.main.en)}, ${q(d.dessert.hu)}, ${q(d.dessert.en)})`)
    .join(",\n") + "\non conflict (weekday) do nothing;",
);
const tables = [
  ["T1", 2, "window"], ["T2", 2, "window"], ["T3", 4, "inside"], ["T4", 4, "inside"], ["T5", 4, "inside"],
  ["T6", 6, "inside"], ["T7", 6, "inside"], ["T8", 8, "inside"], ["B1", 2, "bar"], ["B2", 2, "bar"],
  ["K1", 4, "terrace"], ["K2", 4, "terrace"],
];
lines.push(
  "insert into public.dining_tables (label, seats, area) values",
  tables.map(([l, s, a]) => `(${q(l)}, ${s}, ${q(a)})`).join(",\n") + "\non conflict (label) do nothing;",
);
// First admin + owner alert inbox: ADMIN_EMAIL=you@example.com node --experimental-strip-types scripts/gen-seed.mts
const admin = process.env.ADMIN_EMAIL ?? "admin@example.com";
lines.push(`insert into public.staff_invites (email, role, name) values (${q(admin)}, 'admin', 'Owner') on conflict (email) do nothing;`);
lines.push(`update public.settings set owner_email = ${q(admin)} where owner_email is null;`);
lines.push("commit;");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log("seed.sql written:", menuItems.length, "items");
